# .pre-commit-config.yaml
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [
          --auto-fix,
          --no-sort-keys
        ]

  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        language: system
        entry: powershell ./scripts/pre-commit-dotnet-format.ps1
        files: ^backend/.*\.cs$
