trigger: none

resources:
  pipelines:
    - pipeline: LACSUIProdBuild
      source: LACC-UI-prod-build
      trigger:
        branches:
          include:
            - main

variables:
  web-app-name: "lacc-app-ui-spa-dev"
  build-agent: "HSK Production Pool"
  azure-subscription: "HSK Prod (via service principal)"
  resource-group: "rg-hsk-uma-prod"
  environmentName: "HSK-prod"
  build-pipeline: "HSKUIProdBuild"
stages:
  - stage: Deploy
    displayName: Deploy to PROD
    pool:
      'LaCC Pre-Prod Build Agents'
          
    jobs:
      - deployment: CI_Deploy_LACCUI_DEV
        environment: 'LACC_DEVELOPMENT'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'
                    resourceGroupName: 'rg-lacc-dev'
                    appType: "webAppLinux"
                    WebAppName: "$(web-app-name)"
                    packageForLinux: "$(Pipeline.Workspace)/$(build-pipeline)/lacc-ui-dev-drop"
                    RuntimeStack: "NODE|22-lts"
                    StartupCommand: "pm2 serve /home/site/wwwroot/ --no-daemon --spa" 
                  displayName: "Deploy LACC UI React App to Dev"
                  retryCountOnTaskFailure: 1



