# Deploy the LACC UI React app to an Azure App Service instance
# Uses the pre-installed 'PM2' app that comes with Node on Azure

parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - qa
      - prod

trigger: none

resources:
  pipelines:
    - pipeline: 'LACCUIBuild'
      source: 'LACC UI- Build, Test & Package'
      trigger:
        branches:
          include:
            - main
        stages:
          - Build_And_Test_UI
        event: 
          include:
            - push
          exclude:
            - pullrequest

variables:
  - name: environmentSuffix
    value: ${{ lower(parameters.environment) }}
  - name: resourceGroupName
    value: 'rg-lacc-$(environmentSuffix)-temp'
  - name: appName
    value: 'app-lacc-ui-$(environmentSuffix)-temp'
  - name: build-agent
    value: 'ubuntu-latest'
  - name: azureSubscription
    ${{ if eq(parameters.environment, 'dev') }}:
      value: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'
    ${{ if eq(parameters.environment, 'qa') }}:
      value: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'
    ${{ if eq(parameters.environment, 'prod') }}:
      value: 'Azure Pipeline: Large and Complex Cases - Prod'

stages:
  - stage: Deploy_${{ variables.environmentSuffix }}
    displayName: 'Deploy to ${{ variables.environmentSuffix }}'
    pool:
      vmImage: $(build-agent)
    jobs:
      - job: CI_Deploy_LACCUI_${{ variables.environmentSuffix }}
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download UI Build Artifact'
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: 'LACC UI- Build, Test & Package'
              buildVersionToDownload: 'latest'
              artifactName: 'lacc-ui-$(environmentSuffix)-drop'
              downloadPath: '$(Pipeline.Workspace)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: $(azureSubscription)
              resourceGroupName: $(resourceGroupName)
              appType: 'webAppLinux'
              WebAppName: '$(appName)'
              packageForLinux: '$(Pipeline.Workspace)/lacc-ui-$(environmentSuffix)-drop/*.zip'
              RuntimeStack: 'NODE|20-lts'
              StartupCommand: 'pm2 serve /home/site/wwwroot/ --no-daemon --spa'
              
            displayName: 'Deploy LACC UI to ${{ variables.environmentSuffix }}'
            retryCountOnTaskFailure: 1 