---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ComplexCasesNetworkingBuild
      source: LaCC Networking - Integration - Build
      trigger: true
            
variables:
  - group: complex-cases-secure-pre-prod
  - group: complex-cases-global
  - group: complex-cases-terraform
    
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Apply_INT
    displayName: INT > Apply Terraform
    jobs:
      - deployment: Apply_Networking_Terraform
        environment: "Complex_Cases_INT"
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/stages/jobs/tasks/task_get-credentials.yml
                  parameters:
                    azureSubscription: $(azure-subscription-pre-prod)
                    
                - template: ../templates/stages/jobs/tasks/task_apply-terraform.yml
                  parameters:
                    targetBuild: ComplexCasesNetworkingBuild
                    targetTerraformArtifact: "terraform-files-networking"
                    targetLabel: "INT"
                    targetName: "Networking Terraform CI Deployment"
                    targetPlanName: "int"
                    terraformStorageAccount: $(terraform-storage-name-int)
                    terraformContainerName: $(terraform-container-name-networking-int)
                    terraformStateKey: $(terraform-state-file)
                    terraformStateAccessKey: $(terraform-storage-shared-key-int)
                    armClientId: $(clientId)
                    armClientSecret: $(clientSecret)
                    armTenantId: $(tenantId)
                    armSubscriptionId: $(subscriptionId)
