schedules:
  - cron: '0 3 * * Tue-Sat'
    displayName: 'Weekday 3am UTC cleanup'
    branches:
      include:
        - main
    always: true

trigger: none

pool: 'LACC PreProd Pool'

variables:
  - group: lacc-automated-testing-dev
  - group: lacc-backend-config-dev

jobs:
  - job: cleanup_test_files
    displayName: 'Cleanup Test Files from Egress and Shared Drive'
    steps:
      - script: |
          if command -v pwsh &> /dev/null; then 
            echo "PowerShell already installed. Skipping installation."
          else 
            echo "Installing PowerShell..."
            bash '$(System.DefaultWorkingDirectory)/devops-pipelines/scripts/installPowershell.sh'
            echo "Powershel version: $(pwsh -v)"
          fi
        displayName: 'Install PowerShell'

      - task: PowerShell@2
        displayName: 'Clear integration-tests Egress folder'
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)/devops-pipelines/scripts/test-automation-cleanup/Clear-EgressFolder.ps1'
          arguments: >
            -BaseUrl $(EgressOptionsUrl)
            -ServiceAccountAuth $(EgressServiceAccountAuth)
            -WorkspaceId $(EgressWorkspaceId)
            -FolderName "integration-tests"
            -Force

      - task: PowerShell@2
        displayName: 'Clear existingCaseAutomation Egress folders'
        condition: succeededOrFailed()
        inputs:
          targetType: 'inline'
          workingDirectory: '$(System.DefaultWorkingDirectory)/devops-pipelines/scripts/test-automation-cleanup'
          script: |
            $folders = @(
              '3. Unused - disclosed'
              '4. Served Evidence'
            )

            $failedFolders = @()

            foreach ($folder in $folders) {
              Write-Host "Attempting to clear contents of folder '$folder'..."

              try {
                & ./Clear-EgressFolder.ps1 `
                  -BaseUrl "$(EgressOptionsUrl)" `
                  -ServiceAccountAuth "$(EgressServiceAccountAuth)" `
                  -WorkspaceId "$(E2eEgressWorkspaceId)" `
                  -FolderName $folder `
                  -Force
              }
              catch {
                Write-Host "[ERROR] $_"
                $failedFolders += @{
                  folderName = $folder
                  error = $_
                }
              }
            }

            if ($failedFolders.Count -gt 0) {
              Write-Host "One or more folders failed to clear:"
              foreach ($failed in $failedFolders) {
                Write-Host " - $($failed.folderName) : $($failed.error) "
              }

              throw "Egress cleanup failed for $($failedFolders.Count) folder(s)."
            }

            Write-Host "All folders cleared successfully."

      # The following step is temporarily here while Kamesh is testing his E2E tests.
      # It can be moved to the CMRC repo once the E2E tests are available there.
      # In Transfer Materials we won't be creating new Egress Workspaces
      - task: PowerShell@2
        displayName: 'Remove generated Automation-Testing workspaces'
        condition: succeededOrFailed()
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)/devops-pipelines/scripts/test-automation-cleanup/Remove-EgressWorkspacesByPrefix.ps1'
          arguments: >
            -BaseUrl $(EgressOptionsUrl)
            -ServiceAccountAuth $(EgressServiceAccountAuth)
            -WorkspaceNamePrefix "AUTOMATION-TESTING"
            -Force

      - task: PowerShell@2
        displayName: 'Clear integration-tests NetApp folder'
        condition: succeededOrFailed()
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)/devops-pipelines/scripts/test-automation-cleanup/Clear-SharedDriveFolder.ps1'
          arguments: >
            -ClientId $(CallingAppValidAudience)
            -TenantId $(TenantId)
            -AadUsername $(AadUserName)
            -AadPassword $(AadUserPassword)
            -CaseId $(IntegrationTestsCaseId)
            -FolderPath "integration-tests"
            -BaseUrl $(LccApiBaseUrl)

      # # The following step is disabled while Kamesh is working on the E2E tests. 
      # # Once E2E test are merged, the following should be enabled:

      # - task: PowerShell@2
      #   displayName: 'Clear E2E tests NetApp folder'
      #   condition: succeededOrFailed()
      #   inputs:
      #     filePath: '$(System.DefaultWorkingDirectory)/devops-pipelines/scripts/test-automation-cleanup/Clear-SharedDriveFolder.ps1'
      #     arguments: >
      #       -ClientId $(CallingAppValidAudience)
      #       -TenantId $(TenantId)
      #       -AadUsername $(AadUserName)
      #       -AadPassword $(AadUserPassword)
      #       -CaseId $(E2eTestsCaseId)
      #       -FolderPath "existingCaseAutomation"
  