---
parameters:
  - name: targetSuffix
    type: string
  - name: azureSubscription
    type: string

jobs:
  - job: Pause_Pipeline
    condition: succeeded()
    displayName: Pause for 2 minutes
    steps:
      - template: tasks/task_pause-pipeline.yml

  - job: Swap_API_Slot
    dependsOn: Pause_Pipeline
    condition: succeeded()
    strategy:
      matrix:
        API:
          Name: "API"
          AppServiceName: "LaCC${{ parameters.targetSuffix }}-api"
    displayName: Swap
    steps:
      - checkout: none
      - task: AzureAppServiceManage@0
        displayName: Swap slot
        inputs:
          action: "Swap Slots"
          sourceSlot: "staging"
          azureSubscription: ${{ parameters.azureSubscription }}
          resourceGroupName: "rg-LaCC${{ parameters.targetSuffix }}"
          webAppName: $(AppServiceName)
          PreserveVnet: true

  #- job: Swap_UI_Slot
  #  dependsOn: Pause_Pipeline
  #  condition: succeeded()
  #  strategy:
  #    matrix:
  #      SPA:
  #        Name: "UI"
  #        AppServiceName: "LaCC${{ parameters.targetSuffix }}-ui"
  #  displayName: Swap
  #  steps:
  #    - checkout: none
  #    - task: AzureAppServiceManage@0
  #      displayName: Swap slot
  #      inputs:
  #        action: "Swap Slots"
  #        sourceSlot: "staging"
  #        azureSubscription: ${{ parameters.azureSubscription }}
  #        resourceGroupName: "rg-LaCC${{ parameters.targetSuffix }}"
  #        webAppName: $(AppServiceName)
  #        PreserveVnet: true
  