param (
    [string]$ProjectPath = "ui-spa",
    [string]$CoverageSummaryPath = "coverage/coverage-final.json",
    [string]$CoberturaPath = "coverage/cobertura-coverage.xml",
    [string]$LcovReportPath = "coverage/lcov-report",
    [string]$OutputReportPath = "coverage/html-enhanced"
)

$ErrorActionPreference = 'Continue'
# Navigate to UI directory
Set-Location $ProjectPath

if (Test-Path $CoberturaPath) {
    Write-Host "Generating enhanced coverage report..."

    # Create enhanced HTML report directory
    New-Item -Path $OutputReportPath -ItemType Directory -Force

    # Copy existing HTML report
    if (Test-Path $LcovReportPath) {
        Copy-Item -Path "coverage/lcov-report/*" -Destination "coverage/html-enhanced/" -Recurse -Force
    }

    # Generate a simple coverage summary
    if (Test-Path $CoverageSummaryPath) {
        Write-Host "Processing coverage summary..."
        $summary = Get-Content $CoverageSummaryPath | ConvertFrom-Json
        $total = $summary.total

        $buildDate = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        $buildNumber = if ($env:BUILD_BUILDNUMBER) { $env:BUILD_BUILDNUMBER } else { "Local" }

        $htmlContent = @"
<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0'>
<title>CPS Complex Cases UI - Coverage Report</title>
<style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
    .header { background: #2563eb; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
    .header h1 { margin: 0; font-size: 24px; }
    .header p { margin: 5px 0 0 0; opacity: 0.9; }
    .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }
    .metric { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); text-align: center; }
    .metric h3 { margin: 0 0 10px 0; color: #333; }
    .metric .value { font-size: 32px; font-weight: bold; margin: 10px 0; }
    .lines .value { color: #28a745; }
    .functions .value { color: #007bff; }
    .branches .value { color: #ffc107; }
    .statements .value { color: #dc3545; }
    .footer { text-align: center; margin-top: 20px; color: #666; font-size: 14px; }
</style>
</head>
<body>
<div class='header'>
    <h1>🎯 CPS Complex Cases UI - Coverage Report</h1>
    <p>Generated on $buildDate | Build: $buildNumber</p>
</div>
<div class='metrics'>
    <div class='metric lines'>
    <h3>Lines</h3>
    <div class='value'>$([math]::Round($total.lines.pct))%</div>
    <p>$($total.lines.covered)/$($total.lines.total)</p>
    </div>
    <div class='metric functions'>
    <h3>Functions</h3>
    <div class='value'>$([math]::Round($total.functions.pct))%</div>
    <p>$($total.functions.covered)/$($total.functions.total)</p>
    </div>
    <div class='metric branches'>
    <h3>Branches</h3>
    <div class='value'>$([math]::Round($total.branches.pct))%</div>
    <p>$($total.branches.covered)/$($total.branches.total)</p>
    </div>
    <div class='metric statements'>
    <h3>Statements</h3>
    <div class='value'>$([math]::Round($total.statements.pct))%</div>
    <p>$($total.statements.covered)/$($total.statements.total)</p>
    </div>
</div>
<div class='footer'>
    <p>Generated by Vitest Coverage | Enhanced for CPS Complex Cases Project</p>
</div>
</body>
</html>
"@

        $htmlContent | Out-File -FilePath "coverage/html-enhanced/enhanced-report.html" -Encoding UTF8
        Write-Host "Enhanced HTML coverage report generated successfully"
    }

    Write-Host "Coverage report location: $ProjectPath/coverage/html-enhanced"
} else {
    Write-Host "No coverage files found - skipping enhanced report generation"
}