---

steps:
  - bash: |
      until sudo apt-get -y update && sudo apt-get install unzip zip jq -y
      do
      echo "Try again"
      sleep 2
      done
      
      DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
      sudo apt-get update
      sudo apt-get update -y && sudo apt-get install -y dotnet-sdk-8.0
    displayName: Install DotNet 8 SDK