---

steps:
  - bash: |
      echo '==== Update package sources ===='
      until sudo apt-get -yq update
      do
      echo "Try again"
      sleep 2
      done
      
      echo '==== Install Mono ===='
      sudo apt-get install -y mono-complete
    displayName: Install Mono