---

steps:
  - bash: |
      echo '==== Update package sources ===='
      until sudo apt-get -yq update
      do
      echo "Try again"
      sleep 2
      done
      
      echo '==== Azure CLI ===='
      curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    displayName: Install Mono