---

steps:
  - bash: |
      echo '==== Update package sources ===='
      until sudo apt-get -y update
      do
      echo "Try again"
      sleep 2
      done
      
      DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
      
      echo '==== Install Mono ===='
      sudo apt-get update -yq
      sudo apt-get install -y mono-complete
      
      echo '==== NuGet ===='
      sudo curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      sudo chmod +x /usr/local/bin/nuget.exe
    displayName: Install NuGet