---

steps:
  - bash: |
      echo '==== Update package sources ===='
      until sudo apt-get -y update
      do
      echo "Try again"
      sleep 2
      done
      
      DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
      
      echo '==== PowerShell ===='
      sudo snap install powershell --classic
    displayName: Install PowerShell