---
parameters:
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: targetSuffix
    type: string
  - name: appInsightsKey
    type: string
  - name: azureSubscription
    type: string

steps:
  # download scripts artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Download Scripts
    artifact: 'complex-cases-script-files'

  # send custom event to AppInsights
  - template: task_send-to-app-insights.yml
    parameters:
      appInsightsKey: ${{ parameters.appInsightsKey }}
      targetBuild: ${{ parameters.targetBuild }}
      message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Publish API - Started"

  # download text-extractor build artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Deploy > Download API Build
    artifact: "complex-cases-api-drop"

  # Deploy Related Codebase to Env
  - task: AzureFunctionApp@1
    displayName: 'Deploy API as an Azure Function App to ${{ parameters.targetLabel }}'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appType: functionAppLinux
      appName: "cc${{ parameters.targetSuffix }}-api"
      package: $(Pipeline.Workspace)/${{ parameters.targetBuild }}/complex-cases-api-drop
      deployToSlotOrASE: true
      resourceGroupName: "rg-complex-cases${{ parameters.targetSuffix }}"
      slotName: "staging"

  # send custom event to AppInsights
  - template: task_send-to-app-insights.yml
    parameters:
      appInsightsKey: ${{ parameters.appInsightsKey }}
      targetBuild: ${{ parameters.targetBuild }}
      message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Publish API - Completed"