---
parameters:
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: targetSuffix
    type: string
  - name: appInsightsKey
    type: string
  - name: azureSubscription
    type: string

steps:
  # download scripts artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Download Scripts
    artifact: 'complex-cases-script-files'

  # send custom event to AppInsights
  - template: task_send-to-app-insights.yml
    parameters:
      appInsightsKey: ${{ parameters.appInsightsKey }}
      targetBuild: ${{ parameters.targetBuild }}
      message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Publish UI - Started"

  # download UI build artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Deploy > Download UI Build
    artifact: "complex-cases-ui-drop"

  # Deploy Related Codebase to Env
  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy UI as an App Service to ${{ parameters.targetLabel }}'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appType: webAppLinux
      WebAppName: "cc${{ parameters.targetSuffix }}-ui"
      packageForLinux: $(Pipeline.Workspace)/${{ parameters.targetBuild }}/complex-cases-ui-drop
      deployToSlotOrASE: true
      resourceGroupName: "rg-complex-cases${{ parameters.targetSuffix }}"
      slotName: "staging"

  # send custom event to AppInsights
  - template: task_send-to-app-insights.yml
    parameters:
      appInsightsKey: ${{ parameters.appInsightsKey }}
      targetBuild: ${{ parameters.targetBuild }}
      message: "${{ parameters.targetLabel }} ${{ parameters.targetName }}: Publish UI - Completed"