parameters:
- name: environment
  type: string
  default: dev
- name: dependsOn
  type: object
  default: []

pool: 'LACC PreProd Pool'

jobs:
- job: run_e2e_tests
  dependsOn: ${{ parameters.dependsOn }}
  variables:
  - group: lacc-backend-secrets-${{ parameters.environment }}
  - group: lacc-backend-config-${{ parameters.environment }}
  - group: lacc-automated-testing-${{ parameters.environment }}

  steps:
  - task: UseNode@1
    displayName: 'Use Node.js'
    inputs:
      version: '20.x'

  - script: |
      if command -v pwsh &> /dev/null; then 
        echo "PowerShell already installed. Skipping installation."
      else 
        echo "Installing PowerShell..."
        bash '$(System.DefaultWorkingDirectory)/devops-pipelines/scripts/installPowershell.sh'
        echo "Powershel version: $(pwsh -v)"
      fi
    displayName: 'Install PowerShell'

  - task: PowerShell@2
    displayName: 'Run E2E Tests'
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/e2e/postman'
      filePath: '$(System.DefaultWorkingDirectory)/e2e/postman/Run-E2E-Tests.ps1'
      arguments: '-SizeMB 100 -StopOnFailure'
    env:
      LCC_UI_URL: "https://lacc-app-ui-spa-${{parameters.environment}}.azurewebsites.net"
      LCC_API_BASE_URL: "https://fa-lacc-api-${{parameters.environment}}.azurewebsites.net"
      LCC_TENANT_ID: $(TenantId)
      LCC_API_CLIENT_ID: $(CallingAppValidAudience)
      LCC_AZURE_USERNAME: $(AadUserName)
      LCC_AZURE_PASSWORD: $(AadUserPassword)
      LCC_CMS_USERNAME: $(CmsUserName)
      LCC_CMS_PASSWORD: $(CmsUserPassword)
      LCC_CASE_API_BASE_URL: "https://fa-cm-api-${{parameters.environment}}.azurewebsites.net"
      LCC_DDEI_BASE_URL: $(DDEIOptionsBaseUrl)
      LCC_DDEI_ACCESS_KEY: $(DDEIOptionsAccessKey)
      LCC_EGRESS_BASE_URL: $(EgressOptionsUrl)
      LCC_EGRESS_SERVICE_ACCOUNT_AUTH: $(EgressServiceAccountAuth)

  - script: |
      echo "Moving newman reports to Artifact Staging Directory..."
      mv -f $(System.DefaultWorkingDirectory)/e2e/postman/newman-reports/* $(Build.ArtifactStagingDirectory)
      
      echo "Showing contents of Artifact Staging Directory:"
      cd $(Build.ArtifactStagingDirectory)
      ls .

      echo "Moving HTML reports into a newly created html-reports directory..."
      mkdir html-reports
      mv *.html html-reports

      echo "Showing contents of html-reports directory:"
      ls html-reports
    displayName: 'Stage Reports for Publishing'
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Build.ArtifactStagingDirectory)/*.xml'
    displayName: 'Publish Newman Report'
    condition: succeededOrFailed()
    
  - publish: '$(Build.ArtifactStagingDirectory)/html-reports'
    artifact: '${{parameters.environment}}-NewmanReportsHTML'
    condition: succeededOrFailed()

  - task: PowerShell@2
    displayName: 'Cleanup Egress Test Workspace'
    condition: eq(variables['isTestWorkspaceCreated'], true)
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/e2e/postman'
      filePath: '$(System.DefaultWorkingDirectory)/e2e/postman/Teardown-EgressWorkspace.ps1'
      arguments: '-WorkspaceId $(egressWorkspaceId)'
    env:
      LCC_EGRESS_BASE_URL: $(EgressOptionsUrl)
      LCC_EGRESS_SERVICE_ACCOUNT_AUTH: $(EgressServiceAccountAuth)