parameters:
- name: environment
  type: string
  default: dev
- name: agentPool
  type: string
  default: LACC PreProd Pool
- name: dependsOn
  type: object
  default: []

jobs:
- job: run_e2e_tests
  pool: ${{ parameters.agentPool }}
  dependsOn: ${{ parameters.dependsOn }}
  variables:
  - group: lacc-backend-secrets-${{ parameters.environment }}
  - group: lacc-backend-config-${{ parameters.environment }}
  - group: lacc-automated-testing-${{ parameters.environment }}

  steps:
  - task: UseNode@1
    displayName: 'Use Node.js'
    inputs:
      version: '20.x'

  - script: |
      if command -v pwsh &> /dev/null; then 
        echo "PowerShell already installed. Skipping installation."
      else 
        echo "Installing PowerShell..."
        bash '$(System.DefaultWorkingDirectory)/devops-pipelines/scripts/installPowershell.sh'
        echo "Powershel version: $(pwsh -v)"
      fi
    displayName: 'Install PowerShell'

  - task: PowerShell@2
    displayName: 'Run E2E Tests'
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/e2e/postman'
      filePath: '$(System.DefaultWorkingDirectory)/e2e/postman/Run-E2E-Tests.ps1'
      arguments: >
        -SizeMB 7 
        -StopOnFailure
    env:
      LCC_BASE_URL: "https://fa-lacc-api-${{parameters.environment}}.azurewebsites.net"
      LCC_TENANT_ID: $(TenantId)
      LCC_API_CLIENT_ID: $(CallingAppValidAudience)
      LCC_AZURE_USERNAME: $(AadUserName)
      LCC_AZURE_PASSWORD: $(AadUserPassword)
      LCC_CMS_USERNAME: $(CmsUserName)
      LCC_CMS_PASSWORD: $(CmsUserPassword)
      LCC_DDEI_BASE_URL: $(DDEIOptionsBaseUrl)
      LCC_DDEI_ACCESS_KEY: $(DDEIOptionsAccessKey)
      LCC_EGRESS_BASE_URL: $(EgressOptionsUrl)
      LCC_EGRESS_SERVICE_ACCOUNT_AUTH: $(EgressServiceAccountAuth)
      LCC_DEFAULT_CASE_ID: $(CmsTestCaseId)
      LCC_DEFAULT_CASE_URN: $(CmsTestUrn)
      LCC_DEFAULT_WORKSPACE_ID: $(EgressWorkspaceId)
      LCC_DEFAULT_WORKSPACE_NAME: $(CmsTestOperationName)

  - script: |
      echo "Moving newman reports to Artifact Staging Directory..."
      mv -f $(System.DefaultWorkingDirectory)/e2e/postman/newman-reports/* $(Build.ArtifactStagingDirectory)
      
      echo "Showing contents of Artifact Staging Directory:"
      cd $(Build.ArtifactStagingDirectory)
      ls .

      echo "Moving HTML reports into a newly created html-reports directory..."
      mkdir html-reports
      mv *.html html-reports

      echo "Showing contents of html-reports directory:"
      ls html-reports
    displayName: 'Stage Reports for Publishing'
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Build.ArtifactStagingDirectory)/*.xml'
    displayName: 'Publish Newman Report'
    condition: succeededOrFailed()
    
  - publish: '$(Build.ArtifactStagingDirectory)/html-reports'
    artifact: '${{parameters.environment}}-NewmanReportsHTML'
    condition: succeededOrFailed()

  # - task: PowerShell@2
  #   displayName: 'Cleanup Egress Test Files'
  #   condition: eq(variables['isFilesUploaded'], 'true') #isFilesUploaded and egressFileIds (below) variables are set during the Run-E2E-Tests.ps1 script run
  #   inputs:
  #     workingDirectory: '$(System.DefaultWorkingDirectory)/e2e/postman'
  #     filePath: '$(System.DefaultWorkingDirectory)/e2e/postman/Teardown-EgressTestFiles.ps1'
  #     arguments: > 
  #       -DeleteFiles
  #       -WorkspaceId $(EgressWorkspaceId)
  #       -FileIds $(egressFileIds)
  #       -Force
  #   env:
  #     LCC_EGRESS_BASE_URL: $(EgressOptionsUrl)
  #     LCC_EGRESS_SERVICE_ACCOUNT_AUTH: $(EgressServiceAccountAuth)