parameters:
  - name: instructions
    type: string
    default: "The pipeline needs your approval to continue."
  - name: notifyUsers
    type: string
    default: ""
  - name: approvers
    type: string
    default: ""
  - name: agentPool
    type: string
    default: "LACC PreProd Pool"

jobs:
  - job: Set_Flag
    displayName: "Set the 'isFriday' Flag"
    pool: ${{ parameters.agentPool }}
    steps:
      - script: |
          isFriday=false

          echo "Fetching the day of the week. This will determine which Manual_Validation job to run..."
          dayOfWeek=$(TZ=Europe/London date +%A)

          if [ "$dayOfWeek" == "Friday" ]; then
            isFriday=true
          fi

          echo "Today is $dayOfWeek. Setting isFriday to $isFriday."
          echo "##vso[task.setVariable variable=isFriday;isOutput=true]$isFriday"
        name: SetFlag
        displayName: "Determine if Today is Friday"

  - job: Manual_Validation
    dependsOn: Set_Flag
    pool: server
    timeoutInMinutes: 4380
    variables:
      isFriday: $[ eq(dependencies.Set_Flag.outputs['SetFlag.isFriday'], 'true') ]
    steps:
      - task: ManualValidation@1
        displayName: Request Validation
        condition: eq(variables.isFriday, 'false')
        timeoutInMinutes: 1440
        inputs:
          notifyUsers: ${{ parameters.notifyUsers }}
          approvers: ${{ parameters.approvers }}
          allowApproversToApproveTheirOwnRuns: true
          instructions: ${{ parameters.instructions }}
          onTimeout: "reject"

      - task: ManualValidation@1
        displayName: Request Validation (Friday)
        condition: eq(variables.isFriday, 'true')
        timeoutInMinutes: 4320
        inputs:
          notifyUsers: ${{ parameters.notifyUsers }}
          approvers: ${{ parameters.approvers }}
          allowApproversToApproveTheirOwnRuns: true
          instructions: ${{ parameters.instructions }}
          onTimeout: "reject"
