---
parameters:
  - name: buildAgentName
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetSuffix
    type: string
  - name: azureSubscription
    type: string

stages:
  - stage: Swap_${{ parameters.targetLabel }}
    pool:
      name: ${{ parameters.buildAgentName }}
    displayName: ${{ parameters.targetLabel }} > Swap Slots
    dependsOn:
      - Apply_${{ parameters.targetLabel }}
      - Deploy_${{ parameters.targetLabel }}
    condition: succeeded()
    jobs:
      - template: jobs/job_swap-slots.yml
        parameters:
          targetSuffix: ${{ parameters.targetSuffix }}
          azureSubscription: ${{ parameters.azureSubscription }}
