---
parameters:
  - name: buildAgentName
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: appInsightsKey
    type: string
  - name: targetSuffix
    type: string
  - name: azureSubscription
    type: string
  
stages:
  - stage: Deploy_${{ parameters.targetLabel }}
    pool:
      name: ${{ parameters.buildAgentName }}
    displayName: Deploy
    condition: succeeded()
    dependsOn: Apply_${{ parameters.targetLabel }}
    jobs:
      - job: Log_Start_Codebase
        condition: succeeded()
        displayName: Log Start
        steps:
          - template: jobs/tasks/task_log-start-deployment.yml
            parameters:
              targetBuild: ${{ parameters.targetBuild }}
              targetLabel: ${{ parameters.targetLabel }}
              targetName: "Codebase CI Deployment"
              appInsightsKey: ${{ parameters.appInsightsKey }}

      - job: Deploy_API
        dependsOn: Log_Start_Codebase
        displayName: Deploy API
        condition: succeeded()
        steps:
          - template: jobs/tasks/task_deploy-api.yml
            parameters:
              targetBuild: ${{ parameters.targetBuild }}
              targetLabel: ${{ parameters.targetLabel }}
              targetName: "API Deployment"
              targetSuffix: ${{ parameters.targetSuffix }}
              appInsightsKey: ${{ parameters.appInsightsKey }}
              azureSubscription: ${{ parameters.azureSubscription }}

      - job: Deploy_UI
        dependsOn: Log_Start_Codebase
        displayName: Deploy UI
        condition: succeeded()
        steps:
          - template: jobs/tasks/task_deploy-ui.yml
            parameters:
              targetBuild: ${{ parameters.targetBuild }}
              targetLabel: ${{ parameters.targetLabel }}
              targetName: "SPA Deployment"
              targetSuffix: ${{ parameters.targetSuffix }}
              appInsightsKey: ${{ parameters.appInsightsKey }}
              azureSubscription: ${{ parameters.azureSubscription }}

      - job: Log_Result_Codebase_Ended
        condition: succeeded()
        displayName: Log End
        dependsOn:
          - Deploy_API
          - Deploy_UI
        steps:
          - template: jobs/tasks/task_log-result-deployment.yml
            parameters:
              targetBuild: ${{ parameters.targetBuild }}
              targetLabel: ${{ parameters.targetLabel }}
              targetName: "Codebase CI Deployment"
              appInsightsKey: ${{ parameters.appInsightsKey }}
              devOpsPatToken: $(System.AccessToken)
