---
parameters:
  - name: buildAgentName
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
    
stages:
  - stage: Update_GitHub_Tag_${{ parameters.targetLabel }}
    pool:
      name: ${{ parameters.buildAgentName }}
    displayName: Update Tag
    dependsOn: Create_Commit_Report_${{ parameters.targetLabel }}
    condition: succeeded()
    jobs:
      - job: Update_Github_Tag
        steps:
          - template: jobs/tasks/task_update-github-tag.yml
            parameters:
              targetLabel: ${{ parameters.targetLabel }}
