---
parameters:
  - name: buildAgentName
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetLabelLower
    type: string
  
stages:
  - stage: Create_Commit_Report_${{ parameters.targetLabel }}
    pool:
      name: ${{ parameters.buildAgentName }}
    displayName: Save Report
    dependsOn: Check_Status_${{ parameters.targetLabel }}
    condition: succeeded()
    jobs:
      - job: Create_Commit_Report
        steps:
          - template: jobs/tasks/task_create-commit-report.yml
            parameters:
              targetLabel: ${{ parameters.targetLabel }}
              targetLabelLower: ${{ parameters.targetLabelLower }}
