trigger: none

resources:
  pipelines:
    - pipeline: LACCUIDevBuild
      source: LACC-UI-dev-build
      trigger:
        branches:
          include:
            - 'lcc-166-uipipeline'

variables:
  web-app-name: "lacc-app-ui-spa-dev"
  build-agent: "LaCC Pre-Prod Build Agents"
  azure-subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod"
  resource-group: "rg-lacc-dev"
  environmentName: "LACC_DEVELOPMENT"
  build-pipeline: "LACCUIDevBuild"
stages:
  - stage: Deploy
    displayName: Deploy to Dev
    pool:
      'LaCC Pre-Prod Build Agents'
          
    jobs:
      - deployment: CI_Deploy_LACCUI_DEV
        environment: 'LACC_DEVELOPMENT'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@5
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'
                    appType: 'webAppLinux'
                    WebAppName: 'lacc-app-ui-spa-dev'
                    packageForLinux: '$(System.DefaultWorkingDirectory)/**/LACCUIDevBuild'
                    RuntimeStack: 'NODE|22-lts'
                    StartupCommand: 'npm start'
                    DeploymentTypeLinux: 'oneDeploy'
                # - task: AzureRmWebAppDeployment@4
                #   inputs:
                #     ConnectionType: "AzureRM"
                #     azureSubscription: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'
                #     resourceGroupName: $(resource-group)
                #     appType: "webAppLinux"
                #     WebAppName: "$(web-app-name)"
                #     packageForLinux: "$(Pipeline.Workspace)/$(build-pipeline)/lacc-ui-dev-drop"
                #     RuntimeStack: "NODE|22-lts"
                #     StartupCommand: "pm2 serve /home/site/wwwroot/ --no-daemon --spa" 
                #   displayName: "Deploy LACC UI React App to Dev"
                #   retryCountOnTaskFailure: 1



