---
trigger:
  branches:
    include:
      - 'main'

# resources:
#   repositories:
#     - repository: PipelineTemplates           
#       type: git
#       name: "CPS-Innovation/large-and-complex-cases-pipeline-templates"
#       ref: refs/heads/main
#       endpoint:  "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service connection


# deploy to Dev
# jobs:
#   - template: templates/ui_spa_pipeline_template.yml
#     parameters:
#       buildAgent: 'LaCC Pre-Prod Build Agents' 
#       nodeVersion: 22
#       webAppName: 'lacc-app-ui-spa-dev'
#       serviceConnectionName: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'

# - stage: Build
#   displayName: Build & Test
#   condition: |
#     eq(variables['Build.Reason'], 'PullRequest')
 
jobs:
  - job: build_and_test
    pool:
      # name: ${{ parameters.buildAgent }}
      vmImage: ubuntu-latest

    steps:  
      - task: Npm@1
        displayName: Install npm dependencies
        inputs:
          command: 'install'  

      - task: Npm@1
        displayName: Build web app package
        inputs:
          command: 'custom'
          customCommand: 'run build'

      - task: Npm@1
        displayName: Run tests
        env:
          CI: 'true'
        inputs:
          command: 'custom'
          customCommand: 'test'
