---
trigger:
  branches:
    include:
      - 'main'

# resources:
#   repositories:
#     - repository: PipelineTemplates           
#       type: git
#       name: "CPS-Innovation/large-and-complex-cases-pipeline-templates"
#       ref: refs/heads/main
#       endpoint:  "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service connection


# deploy to Dev
# jobs:
#   - template: templates/ui_spa_pipeline_template.yml
#     parameters:
#       buildAgent: 'LaCC Pre-Prod Build Agents' 
#       nodeVersion: 22
#       webAppName: 'lacc-app-ui-spa-dev'
#       serviceConnectionName: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'
stages:
  - stage: 'build_And_Test'
    displayName: 'build And Test'
    jobs:
      - job: build_and_test
        condition: eq(variables['Build.Reason'], 'PullRequest')
        pool:
          # name: ${{ parameters.buildAgent }}
          vmImage: ubuntu-latest

        steps:  
          - task: Npm@1
            displayName: Install npm dependencies
            inputs:
              command: 'install'
              workingDir: 'ui-spa/'

          - task: Npm@1
            displayName: Build web app package
            inputs:
              command: 'custom'
              customCommand: 'run build'
              workingDir: 'ui-spa/'
              
          - task: Npm@1
            displayName: Run tests
            env:
              CI: 'true'
            inputs:
              command: 'custom'
              customCommand: test
              workingDir: 'ui-spa/'

  - stage: Build_and_Publish_Artifact
    displayName: 'Build Artifact'
    condition:  eq(variables['Build.Reason'], 'PullRequest')
    dependsOn: 'build_And_Test'
    jobs:
      - job: Build_and_Publish_Artifact
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: Npm@1
            displayName: Install npm dependencies
            inputs:
              command: 'install'
              workingDir: 'ui-spa/'

          - task: Npm@1
            displayName: Build web app package
            env:
              VITE_GATEWAY_BASE_URL: 'api://57c88580-01d4-477d-9b1d-ebb22c8d05af/user_impersonation'
              VITE_CLIENT_ID: 'd0ed05d6-2d0a-43dd-a4f2-56cb56afe6f4'
              VITE_TENANT_ID: '00dd0d1d-d7e6-4338-ac51-565339c7088c'
            inputs:
              command: 'custom'
              customCommand: 'run build'
              workingDir: 'ui-spa/'

          - task: PublishPipelineArtifact@1
            displayName: Publish artifact
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/ui-spa
              artifact: 'lacc-ui-dev-drop'




