# Build the React app and publish the build directory as a pipeline artifact

trigger:
  batch: true
  branches:
    include:
      - main

variables:
  - group: lacc-ui-spa

stages:
  - stage: Build_and_Publish_Artifact
    displayName: 'Build Artifact'
    jobs:
      - job: Build_and_Publish_Artifact
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: Npm@1
            displayName: Install npm dependencies
            inputs:
              command: 'install'
              workingDir: 'ui-spa'

          - task: Npm@1
            displayName: Build web app package
            env:
              VITE_GATEWAY_BASE_URL: $(VITE_GATEWAY_BASE_URL)
              VITE_GATEWAY_SCOPE: $(VITE_GATEWAY_SCOPE)
              VITE_CLIENT_ID: $(VITE_CLIENT_ID)
              VITE_TENANT_ID: $(VITE_TENANT_ID)

            inputs:
              command: 'custom'
              customCommand: 'run build'
              workingDir: 'ui-spa'
              

          - task: PublishPipelineArtifact@1
            displayName: Publish artifact
            inputs:
              targetPath: 'ui-spa/dist'
              artifact: 'lacc-ui-dev-drop'
