# Deploy the LACC UI React app to an Azure App Service instance
# Uses the pre-installed 'PM2' app that comes with Node on Azure

trigger: none

resources:
  pipelines:
    - pipeline: 'LACCUIDevBuild'
      source: LACC-UI-Dev-build
      trigger:
        branches:
          include:
            - main

variables:
  buildConfiguration: 'Release'
  web-app-name: 'lacc-app-ui-spa-dev'
  build-agent: 'LaCC Pre-Prod Build Agents'
  azure-subscription: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'
  resource-group: 'rg-lacc-dev'
  environmentName: 'LACC_DEVELOPMENT'
  build-pipeline: 'LACCUIDevBuild'

stages:
  - stage: Deploy_STAGING
    displayName: Deploy to STAGING
    pool:
      name: $(build-agent)
    jobs:
      - deployment: CI_Deploy_LACCUI_STAGING
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: $(azure-subscription)
                    resourceGroupName: $(resource-group)
                    appType: 'webAppLinux'
                    WebAppName: '$(web-app-name)'
                    packageForLinux: '$(Pipeline.Workspace)/$(build-pipeline)/lacc-ui-dev-drop'
                    RuntimeStack: 'NODE|22-lts'
                    StartupCommand: 'pm2 serve /home/site/wwwroot/ --no-daemon --spa'
                    
                  displayName: 'Deploy LACC UI React App to Dev'
                  retryCountOnTaskFailure: 1

