trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ui-spa/*

pr: none

parameters:
  - name: notifyUsers
    displayName: 'Users to notify by email of pending manual validation'
    type: string
    default: 'Hasan.Ahmed@cps.gov.uk'
  - name: approvers
    displayName: 'Users permitted to approve or reject the manual validation request'
    type: string
    default: 'Hasan.Ahmed@cps.gov.uk'

stages:
  - template: ../templates/ui-build-and-deploy-stages.yml

  - template: ../templates/ui-build-and-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: ${{ parameters.notifyUsers }}
      approvers: ${{ parameters.approvers }}

  # - template: ../templates/ui-build-and-deploy-stages.yml
  #   parameters:
  #     environment: prod
  #     requireValidation: true
  #     notifyUsers: ${{ parameters.notifyUsers }}
  #     approvers: ${{ parameters.approvers }}
  #     agentPool: 'LACC Production Pool'
  #     azureSubscription: 'Azure Pipeline: Large and Complex Cases - Prod'
