trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ui-spa/*

pr: none

variables:
  - group: lacc-deployment-global

stages:
  - template: ../templates/ui-build-and-deploy-stages.yml
    parameters:
      environment: dev
      requireValidation: false

  - template: ../templates/ui-build-and-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: $(notifyUsers)
      approvers: $(approvers)
      deployToSlot: true
      slotName: 'stg'
      
  - template: ../templates/ui-build-and-deploy-stages.yml
    parameters:
      environment: prod
      requireValidation: true
      notifyUsers: $(notifyUsers)
      approvers: $(approvers)
      agentPool: 'LACC Prod Pool'
      azureSubscription: 'Azure Pipeline: Large and Complex Cases - Prod'
      deployToSlot: true
      slotName: 'stg'
