trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ui-spa/*

pr: none

stages:
  - template: ../templates/ui-build-and-deploy-stages.yml
    parameters:
      environment: dev
      requireValidation: false

  - template: ../templates/ui-build-and-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: $(notifyUsers) #defined via Azure Pipelines UI
      approvers: $(approvers) #defined via Azure Pipelines UI

  # - template: ../templates/ui-build-and-deploy-stages.yml
  #   parameters:
  #     environment: prod
  #     requireValidation: true
  #     notifyUsers: $(notifyUsers) #defined via Azure Pipelines UI
  #     approvers: $(approvers) #defined via Azure Pipelines UI
  #     agentPool: 'LACC Production Pool'
  #     azureSubscription: 'Azure Pipeline: Large and Complex Cases - Prod'
