parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - stage
      - prod

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ui-spa/*

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: lacc-ui-config-${{ parameters.environment }}
  - name: nodeVersion
    value: '20.x'
  - name: workingDir
    value: ui-spa

stages:
  - stage: Build_and_Publish_Artifact
    displayName: 'LACC UI - Build & Publish Web App Package'
    jobs:
      - job: Build_and_Publish_Artifact
        displayName: 'Build UI SPA'
        steps:
          - checkout: self
            sparseCheckoutDirectories: '$(workingDir)'

          - task: UseNode@1
            displayName: 'Use Node.js'
            inputs:
              version: '$(nodeVersion)'

          - task: Npm@1
            displayName: 'Install NPM Dependencies'
            inputs:
              command: 'ci'
              workingDir: '$(workingDir)'

          - task: Npm@1
            displayName: 'Build Web App Package'
            inputs:
              command: 'custom'
              customCommand: 'run build'
              workingDir: '$(workingDir)'
            env:
              VITE_GATEWAY_BASE_URL: $(VITE_GATEWAY_BASE_URL)
              VITE_GATEWAY_SCOPE: $(VITE_GATEWAY_SCOPE)
              VITE_CLIENT_ID: $(VITE_CLIENT_ID)
              VITE_TENANT_ID: $(VITE_TENANT_ID) 

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Web App Package'
            inputs:
              targetPath: '$(workingDir)/dist'
              artifact: 'lacc-ui-${{ parameters.environment }}-drop'