# Deploy the LACC UI React app to an Azure App Service instance
# Uses the pre-installed 'PM2' app that comes with Node on Azure

parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - stage
      - prod

trigger:
  batch: true
  branches:
    include:
      - main

pr: none

variables:
  - name: resourceGroupName
    value: 'rg-lacc-${{ parameters.environment }}'
  - name: appName
    value: 'lacc-app-ui-spa-${{ parameters.environment }}'
  - name: build-agent
    value: 'LaCC Pre-Prod Build Agents'
  - name: azureSubscription
    ${{ if ne(parameters.environment, 'prod') }}:
      value: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'
    ${{ else }}:
      value: 'Azure Pipeline: Large and Complex Cases - Prod'

stages:
  - stage: Deploy_${{ parameters.environment }}
    displayName: 'Deploy to ${{ parameters.environment }}'
    pool:
      name: $(build-agent)
    jobs:
      - job: CI_Deploy_LACCUI_${{ parameters.environment }}
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download UI Build Artifact'
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '[TEST]LACC UI - Test & Build'
              buildVersionToDownload: 'latest'
              artifactName: 'lacc-ui-${{ parameters.environment }}-drop'
              downloadPath: '$(Pipeline.Workspace)'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: $(azureSubscription)
              resourceGroupName: $(resourceGroupName)
              appType: 'webAppLinux'
              WebAppName: '$(appName)'
              packageForLinux: '$(Pipeline.Workspace)/lacc-ui-${{ parameters.environment }}-drop/*.zip'
              RuntimeStack: 'NODE|20-lts'
              StartupCommand: 'pm2 serve /home/site/wwwroot/ --no-daemon --spa'
              
            displayName: 'Deploy LACC UI to ${{ parameters.environment }}'
            retryCountOnTaskFailure: 1 