parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - stage
      - prod

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - ui-spa/*

pool:
  vmImage: ubuntu-latest

variables:
  - name: nodeVersion
    value: '20.x'
  - name: workingDir
    value: ui-spa
  - name: covDir
    value: 'coverage'

stages:
  - stage: Build_and_Test_UI
    displayName: 'LACC UI - Build & Test'
    jobs:
      - job: Build_and_Test
        displayName: 'Build & Test App'
        steps:
          - checkout: self
            sparseCheckoutDirectories: ui-spa devops-pipelines/scripts

          - task: UseNode@1
            displayName: 'Use Node.js'
            inputs:
              version: '$(nodeVersion)'

          - task: Npm@1
            displayName: 'Install NPM Dependencies'
            inputs:
              command: 'ci'
              workingDir: '$(workingDir)'

          - task: Npm@1
            displayName: 'Lint Code'
            inputs:
              command: 'custom'
              customCommand: 'run lint'
              workingDir: 'ui-spa'

          - task: Npm@1
            displayName: 'Build Web App Package'
            inputs:
              command: 'custom'
              customCommand: 'run build'
              workingDir: '$(workingDir)'

          - task: Npm@1
            displayName: 'Run UI Unit Tests'
            inputs:
              command: 'custom'
              customCommand: 'run coverage'
              workingDir: '$(workingDir)'

          - task: PublishTestResults@2
            displayName: 'Publish UI Test Results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'ui-spa/$(covDir)/unit-test-results.xml'
              publishRunAttachments: true
            condition: always()

          - template: ../templates/test-e2e.yml

          - script: |
              covDir="coverage"
              
              # Combine the coverage reports for unit and E2E tests
              npx nyc merge $(covDir)/reports $(covDir)/temp/coverage-combined.json

              # Generate a Cobertura coverage report
              npx nyc report --temp-dir $(covDir)/temp --reporter cobertura --report-dir $(covDir)
            displayName: 'Generate Combined Coverage Report'
            workingDirectory: '$(workingDir)'
            condition: always()

          - task: PublishCodeCoverageResults@2
            displayName: 'Publish UI Code Coverage'
            inputs:
              summaryFileLocation: 'ui-spa/$(covDir)/cobertura-coverage.xml'
            condition: always()