trigger: none

pr:
  branches:
    include:
      - development
      - main
  paths:
    include:
      - backend/*

parameters:
  - name: environment
    displayName: "Target Environment"
    type: string
    default: "dev"
    values:
      - dev
      - staging

variables:
  prTargetBranch: $[ variables['System.PullRequest.TargetBranch'] ]
  isManualTrigger: $[ eq(variables['Build.Reason'], 'Manual') ]

pool: "LACC PreProd Pool"

stages:
  - stage: Test_for_Dev
    condition: or(
        eq(variables.prTargetBranch, 'development'),
        and(
          variables.isManualTrigger,
          ${{ eq(parameters.environment, 'dev') }}
        )
      )
    variables:
      - template: ../templates/variables/backend-deploy-vars.yml
        parameters:
          environment: "dev"
      - template: ../templates/variables/fa-config-dev.yml
      - group: lacc-automated-testing-dev
    jobs:
      - template: ../templates/backend-integration-test-job.yml

  - stage: Test_for_Staging
    dependsOn: []
    condition: or(
        eq(variables.prTargetBranch, 'main'),
        and(
          variables.isManualTrigger,
          ${{ eq(parameters.environment, 'staging') }}
        )
      )
    variables:
      - template: ../templates/variables/backend-deploy-vars.yml
        parameters:
          environment: "staging"
      - template: ../templates/variables/fa-config-staging.yml
      - group: lacc-automated-testing-staging
    jobs:
      - template: ../templates/backend-integration-test-job.yml
