trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - backend/*

parameters:
  - name: buildDB
    type: boolean
    default: true
  - name: buildMainApi
    type: boolean
    default: true
  - name: buildFiletransfer
    type: boolean
    default: true

variables:
  - name: buildConfiguration
    value: "Release"
  - name: dotNetVersion
    value: '10.x'
  - name: efVersion
    value: '10.0.*'
  - name: testResultsDirectory
    value: "$(Agent.TempDirectory)/TestResults"

pool: "LACC PreProd Pool"

stages:
  - stage: Build_And_Test_Backend
    displayName: "Build, Test & Package"
    jobs:
      - job: Package_NuGet
        displayName: "Pack and Publish NuGet Package"
        steps:
          - template: ../templates/dotnet-build-steps.yml
            parameters:
              projectPath: "backend/CPS.ComplexCases.API.HttpTelemetry/CPS.ComplexCases.API.HttpTelemetry.csproj"
              projectName: "HttpTelemetry"
              buildConfiguration: $(buildConfiguration)
              dotNetVersion: $(dotNetVersion)
              useLocalNuGet: false
              publishOutput: false
              runTests: false

          - task: DotNetCoreCLI@2
            displayName: "Pack HttpTelemetry"
            inputs:
              command: "pack"
              packagesToPack: "backend/CPS.ComplexCases.API.HttpTelemetry/CPS.ComplexCases.API.HttpTelemetry.csproj"
              outputDir: "$(Build.ArtifactStagingDirectory)"
              arguments: "--configuration $(buildConfiguration) --no-build"

          - publish: "$(Build.ArtifactStagingDirectory)"
            artifact: "localnuget"
            displayName: "Publish HttpTelemetry Package"

      - job: Build_And_Test_Solution
        displayName: "Build & Test Solution"
        dependsOn: Package_NuGet
        steps:
          - template: ../templates/dotnet-build-steps.yml
            parameters:
              projectPath: "backend/CPS.ComplexCases.sln"
              projectName: "Backend Solution"
              buildConfiguration: "$(buildConfiguration)"
              dotNetVersion: $(dotNetVersion)
              useLocalNuGet: true
              publishOutput: false
              runTests: true
              checkFormatting: true
              testResultsDirectory: $(testResultsDirectory)
