parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - stage
      - prod
  - name: updateKeyVault
    displayName: 'Update Key Vault Secrets'
    type: boolean
    default: true
  - name: runDatabaseMigration
    displayName: 'Run Database Migration'
    type: boolean
    default: true
  - name: deployMainAPI
    displayName: 'Deploy Main API'
    type: boolean
    default: true
  - name: deployFileTransferAPI
    displayName: 'Deploy FileTransfer API'
    type: boolean
    default: true

resources:
  pipelines:
  - pipeline: build
    source: 'LACC-BE-dev-build'
    trigger: 
      branches:
        include:
          - main

variables:
  - group: lacc-backend-secrets-${{ parameters.environment }}
  - group: lacc-backend-config-${{ parameters.environment }}
  - name: resourceGroupName
    value: 'rg-lacc-${{ parameters.environment }}' 
  - name: keyVaultName
    value: 'kv-lacc-${{ parameters.environment }}'
  - name: scripts_directory
    value: '$(System.DefaultWorkingDirectory)/devops-pipelines/scripts'
  - name: azureSubscription
    ${{ if ne(parameters.environment, 'prod') }}:
      value: 'Azure Pipeline: Large and Complex Cases - Pre-Prod'
    ${{ else }}:
      value: 'Azure Pipeline: Large and Complex Cases - Prod'

# TODO: conditionally use prod pool for prod      
pool: 'LACC PreProd Pool'

stages:
  - stage: Update_Key_Vault
    displayName: 'LACC - Update Key Vault'
    condition: ${{ eq(parameters.updateKeyVault, true) }}
    jobs:
      - job: Populate_KV
        displayName: 'LACC - Validate Target Environment'
        steps:
          - checkout: self
            sparseCheckoutDirectories: devops-pipelines/scripts
            fetchDepth: 1

          - task: Bash@3
            displayName: 'Ensure Azure CLI'
            inputs:
              targetType: 'inline'
              script: |
                echo "Checking if Azure CLI is installed..."
                
                # Check if az command exists
                if command -v az &> /dev/null; then
                  echo "Azure CLI is already installed"
                  az --version
                  exit 0
                fi

                echo "Azure CLI not found, installing..."
                bash $(scripts_directory)/installAzureCli.sh   

          - task: AzureCLI@2
            displayName: 'LACC - Initialize Key Vault Secrets from Variable Groups'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                bash $(scripts_directory)/populateKV.sh
            env:
              KEY_VAULT_NAME: $(keyVaultName)
              CASE_MANAGEMENT_DATASTORE_CONNECTION: $(CaseManagementDatastoreConnection)
              EGRESS_OPTIONS_USERNAME: $(EgressOptionsUsername)
              EGRESS_OPTIONS_PASSWORD: $(EgressOptionsPassword)
              DDEI_OPTIONS_ACCESS_KEY: $(DDEIOptionsAccessKey)
              NET_APP_OPTIONS_ACCESS_KEY: $(NetAppOptionsAccessKey)
              NET_APP_OPTIONS_SECRET_KEY: $(NetAppOptionsSecretKey)
              FILE_TRANSFER_API_OPTIONS_ACCESS_KEY: $(FileTransferApiOptionsAccessKey)

  - stage: Database_Migration
    displayName: 'LACC - Database Migration'
    ${{ if eq(parameters.updateKeyVault, true) }}:
      dependsOn: 
        - Update_Key_Vault
    condition: ${{ eq(parameters.runDatabaseMigration, true) }}
    jobs:
      - deployment: Deploy_Database_Changes
        displayName: 'LACC - Deploy Database Changes'
        environment: 'LACC-Backend-${{ parameters.environment }}'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  sparseCheckoutDirectories: devops-pipelines/scripts
                  fetchDepth: 1

                - task: Bash@3
                  displayName: 'Ensure Azure CLI'
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "Checking if Azure CLI is installed..."
                      
                      # Check if az command exists
                      if command -v az &> /dev/null; then
                        echo "Azure CLI is already installed"
                        az --version
                        exit 0
                      fi

                      echo "Azure CLI not found, installing..."
                      bash $(scripts_directory)/installAzureCli.sh 

                - download: build
                  artifact: 'database-scripts-drop'

                - script: |
                    echo "Installing the unzip package..."
                    sudo apt-get update
                    sudo apt-get install unzip -y
                  displayName: 'Install unzip'

                - task: ExtractFiles@1
                  displayName: 'Extract Database Scripts'
                  inputs:
                    archiveFilePatterns: '$(Pipeline.Workspace)/build/database-scripts-drop/*.zip'
                    destinationFolder: '$(Pipeline.Workspace)/build/database-scripts'
                    cleanDestinationFolder: true

                - task: AzureCLI@2
                  displayName: 'Run Database Migration'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      bash $(scripts_directory)/updateDatabase.sh
                  env:
                    KEY_VAULT_NAME: $(keyVaultName)
                    MIGRATION_SCRIPT_PATH: '$(Pipeline.Workspace)/build/database-scripts/migration-script.sql'
                
                - template: ../templates/runner-cleanup.yml
                  parameters:
                    buildArtifactDir: 'build'

  - stage: Deploy_Function_Apps
    displayName: 'LACC - Deploy Function Apps'
    jobs:
      - deployment: Deploy_Main_API
        displayName: 'LACC - Deploy Main API Function App'
        condition: ${{ eq(parameters.deployMainAPI, true) }}
        environment: 'LACC-Backend-${{ parameters.environment }}'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/fa-deploy.yml
                  parameters:
                    environment: ${{ parameters.environment }}
                    functionAppName: 'fa-lacc-api-${{ parameters.environment }}'
                    pipelineResourceAlias: 'build'
                    buildArtifactName: 'lacc-main-api-drop'
                    deployToSlot: true
                    slotName: 'fa-lacc-api-dev/test-slot'

                
                - template: ../templates/runner-cleanup.yml
                  parameters:
                    buildArtifactDir: 'build'

      - deployment: Deploy_FileTransfer_API
        displayName: 'LACC - Deploy FileTransfer API Function App'
        condition: ${{ eq(parameters.deployFileTransferAPI, true) }}
        environment: 'LACC-Backend-${{ parameters.environment }}'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/fa-deploy.yml
                  parameters:
                    environment: ${{ parameters.environment }}
                    functionAppName: 'fa-lacc-filetransfer-api-${{ parameters.environment }}'
                    pipelineResourceAlias: 'build'
                    buildArtifactName: 'lacc-filetransfer-api-drop'
                    deployToSlot: false

                - template: ../templates/runner-cleanup.yml
                  parameters:
                    buildArtifactDir: 'build'