trigger: none

pr:
  branches:
    include:
      - development
      - main
  paths:
    include:
      - backend/*

pool: "LACC PreProd Pool"

stages:
  - stage: Test_for_Dev
    condition: $[ eq(variables['System.PullRequest.TargetBranch'], 'development') ]
    variables:
      - template: ../templates/variables/backend-deploy-vars.yml
        parameters:
          environment: "dev"
      - template: ../templates/variables/fa-config-dev.yml
      - group: lacc-automated-testing-dev
    jobs:
     - template: ../templates/backend-integration-test-job.yml

  - stage: Test_for_Staging
    dependsOn: []
    condition: $[ eq(variables['System.PullRequest.TargetBranch'], 'main') ]
    variables:
      - template: ../templates/variables/backend-deploy-vars.yml
        parameters:
          environment: "staging"
      - template: ../templates/variables/fa-config-staging.yml
      - group: lacc-automated-testing-staging
    jobs:
     - template: ../templates/backend-integration-test-job.yml
