resources:
  pipelines:
  - pipeline: build
    source: 'LACC-BE-dev-build'
    trigger: 
      branches:
        include:
          - main

stages:
  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: dev
      requireValidation: false

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: ${{ variables.notifyUsers }}
      approvers: ${{ variables.approvers }}

  # - template: ../templates/backend-deploy-stages.yml
  #   parameters:
  #     environment: prod
  #     requireValidation: true
  #     notifyUsers: ${{ variables.notifyUsers }}
  #     approvers: ${{ variables.approvers }}
  #     agentPool: 'LACC Production Pool'
  #     azureSubscription: 'Azure Pipeline: Large and Complex Cases - Prod'