resources:
  pipelines:
  - pipeline: build
    source: 'LACC-BE-build'
    trigger: 
      branches:
        include:
          - main

variables:
  - group: lacc-deployment-global

stages:
  - stage: Preflight
    displayName: 'Preflight Checks'
    jobs: 
    - job: Set_DeployDB_Flag
      displayName: 'Check If DB Deployment Is Needed'
      steps:
        - download: build
          artifact: database-scripts-drop
          continueOnError: true   
          
        - bash: |
            if [ -d "$(Pipeline.Workspace)/build/database-scripts-drop" ]; then
              echo "DB migrations artifact found"
              echo "##vso[task.setvariable variable=deployDatabase;isOutput=true]true"
            else
              echo "No DB migrations artifact found"
              echo "##vso[task.setvariable variable=deployDatabase;isOutput=true]false"
            fi
          displayName: Detect DB migrations from artifact
          name: checkArtifact

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: dev
      requireValidation: false
      dependsOn: Preflight
      deployDatabase: $[ eq(stageDependencies.Preflight.Set_DeployDB_Flag.outputs['checkArtifact.deployDatabase'], 'true') ]

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      dependsOn: Preflight
      deployDatabase: $[ eq(stageDependencies.Preflight.Set_DeployDB_Flag.outputs['checkArtifact.deployDatabase'], 'true') ]
      notifyUsers: $(preprodNotifyUsers)
      approvers: $(preprodApprovers)
      deployToSlot: true
      slotName: 'stg'
      runPostmanSmokeTest: true

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: prod
      requireValidation: true
      dependsOn: Preflight
      deployDatabase: $[ eq(stageDependencies.Preflight.Set_DeployDB_Flag.outputs['checkArtifact.deployDatabase'], 'true') ]
      notifyUsers: $(prodNotifyUsers)
      approvers: $(prodApprovers)
      agentPool: 'LACC Prod Pool'
      azureSubscription: 'Azure Pipeline: Large and Complex Cases - Prod'
      deployToSlot: true
      slotName: 'stg'