resources:
  pipelines:
  - pipeline: build
    source: 'LACC-BE-dev-build'
    trigger: 
      branches:
        include:
          - main

parameters:
  - name: notifyUsers
    displayName: 'Users to notify by email of pending manual validation'
    type: string
    default: 'Hasan.Ahmed@cps.gov.uk'
  - name: approvers
    displayName: 'Users permitted to approve or reject the manual validation request'
    type: string
    default: 'Hasan.Ahmed@cps.gov.uk'

stages:
  - template: ../templates/backend-deploy-stages.yml
    parameters:

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: ${{ parameters.notifyUsers }}
      approvers: ${{ parameters.approvers }}