resources:
  pipelines:
  - pipeline: build
    source: 'LACC-BE-dev-build'
    trigger: 
      branches:
        include:
          - main

parameters:
  - name: notifyUsers
    displayName: 'Users/groups to notify be email of pending manual validation'
    type: string
    default: 'Hasan Ahmed (I-10)'
  - name: approvers
    displayName: 'Users/groups/project teams permitted to act on a manual validation'
    type: string
    default: 'Hasan Ahmed (Admin), Hasan Ahmed (I-10)'

stages:
  - template: ../templates/backend-deploy-env.yml

  - template: ../templates/backend-deploy-env.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: ${{ parameters.notifyUsers }}
      approvers: ${{ parameters.approvers }}