resources:
  pipelines:
  - pipeline: build
    source: 'LACC-BE-dev-build'
    trigger: 
      branches:
        include:
          - main

stages:
  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: dev
      requireValidation: false

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: $(notifyUsers) #defined via Azure Pipelines UI
      approvers: $(approvers) #defined via Azure Pipelines UI

  # - template: ../templates/backend-deploy-stages.yml
  #   parameters:
  #     environment: prod
  #     requireValidation: true
  #     notifyUsers: $(notifyUsers) #defined via Azure Pipelines UI
  #     approvers: $(approvers) #defined via Azure Pipelines UI
  #     agentPool: 'LACC Production Pool'
  #     azureSubscription: 'Azure Pipeline: Large and Complex Cases - Prod'