resources:
  pipelines:
  - pipeline: build
    source: 'LACC-BE-build'
    trigger: 
      branches:
        include:
          - main

variables:
  - group: lacc-deployment-global

stages:
  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: dev
      requireValidation: false

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: $(preprodNotifyUsers)
      approvers: $(preprodApprovers)
      deployToSlot: true
      slotName: 'stg'

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: prod
      requireValidation: true
      notifyUsers: $(prodNotifyUsers)
      approvers: $(prodApprovers)
      agentPool: 'LACC Prod Pool'
      azureSubscription: 'Azure Pipeline: Large and Complex Cases - Prod'
      deployToSlot: true
      slotName: 'stg'