trigger: none

parameters:
- name: environment
  type: string
  default: 'dev'
  values:
  - dev
  - staging
  - prod

variables:
  - group: lacc-backend-secrets-${{ parameters.environment }}
  - group: lacc-backend-config-${{ parameters.environment }}
  - group: lacc-automated-testing-${{ parameters.environment }}
  - name: buildConfiguration
    value: 'Release'
  - name: dotNetVersion
    value: '8.x'
  - name: testResultsDirectory
    value: '$(Agent.TempDirectory)/TestResults'
  - name: nugetArtifact
    value: 'localnuget'
  - name: nugetArtifactDownloadPath
    value: '$(Build.SourcesDirectory)/localnuget'

pool: 'LACC PreProd Pool'

jobs:
- job: Package_NuGet
  displayName: 'Pack and Publish NuGet Package'
  steps:
    - template: ../templates/dotnet-build-steps.yml
      parameters:
        projectPath: 'backend/CPS.ComplexCases.API.HttpTelemetry/CPS.ComplexCases.API.HttpTelemetry.csproj'
        projectName: 'HttpTelemetry'
        buildConfiguration: $(buildConfiguration)
        dotNetVersion: $(dotNetVersion)
        useLocalNuGet: false
        publishOutput: false
        runTests: false

    - script: |
        mkdir -p $(Build.SourcesDirectory)/localnuget
        rm -f $(Build.SourcesDirectory)/localnuget/*.nupkg
      displayName: 'Prepare local NuGet directory'

    - task: DotNetCoreCLI@2
      displayName: 'Pack HttpTelemetry'
      inputs:
        command: 'pack'
        packagesToPack: 'backend/CPS.ComplexCases.API.HttpTelemetry/CPS.ComplexCases.API.HttpTelemetry.csproj'
        outputDir: '$(Build.SourcesDirectory)/localnuget'
        arguments: '--configuration $(buildConfiguration) --no-build'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish HttpTelemetry Package'
      inputs:
        targetPath: '$(Build.SourcesDirectory)/localnuget'
        artifact: 'localnuget'

- job: Run_Integration_Tests
  displayName: 'Run Integration Test'
  dependsOn: Package_NuGet
  variables:
    Egress.Url: $(EgressOptionsUrl)
    Egress.Username: $(EgressOptionsUsername)
    Egress.Email: $(EgressEmail)
    Egress.Password: $(EgressOptionsPassword)
    Egress.WorkspaceId: $(EgressWorkspaceId)
    Egress.TestDestinationPath: "integration-tests"
    DDEI.BaseUrl: $(DDEIOptionsBaseUrl)
    DDEI.AccessKey: $(DDEIOptionsAccessKey)
    DDEI.Username: $(CmsUserName)
    DDEI.Password: $(CmsUserPassword)
    DDEI.TestCaseId: $(CmsTestCaseId)
    DDEI.TestUrn: $(CmsTestUrn)
    DDEI.TestOperationName: S(CmsTestOperationName)
    DDEI.TestDefendantLastName: $(CmsTestDefendantLastName)
    DDEI:TestCmsAreaCode: $(CmsTestCmsAreaCode)
    Azure.TenantId: $(TenantId)
    Azure.ClientId: $(CallingAppValidAudience)
    Azure.ClientSecret: $(DevAccessClientSecret)
    Azure.UserScope: 'api://$(CallingAppValidAudience)/user_impersonation'
    Azure.TestUserEmail: $(AadUserName)
    Azure.TestUserPassword: $(AadUserPassword)
    NetApp.Url: $(NetAppOptionsUrl)
    NetApp.ClusterUrl: $(NetAppOptionsClusterUrl)
    NetApp.BucketName: $(NetAppOptionsBucketName)
    NetApp.S3ServiceUuid: $(NetAppOptionsS3ServiceUuid)
    NetApp.SessionDurationSeconds: 1800
    NetApp.PepperVersion: $(NetAppOptionsPepperVersion)
    NetApp.TestFolderPrefix: 'integration-tests'
    KeyVault.Url: 'https://kv-lacc-${{parameters.environment}}.vault.azure.net/'
    Postgres.AuthMode: $(PostgresAuthMode)
    Postgres.DbUserName: $(DbUserName)
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK'
      inputs:
        packageType: 'sdk'
        version: $(dotNetVersion)

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Local NuGet Package'
      inputs:
        buildType: 'current'
        artifact: $(nugetArtifact)
        path: $(nugetArtifactDownloadPath)

    - task: Bash@3
      displayName: 'Create NuGet.Config'
      inputs:
        targetType: 'inline'
        script: |
          cat <<EOF > "$(Build.SourcesDirectory)/NuGet.Config"
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <clear />
              <add key="local-packages" value="$(nugetArtifactDownloadPath)" />
              <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
            </packageSources>
            <packageSourceMapping>
              <packageSource key="local-packages">
                <package pattern="CPS.ComplexCases.*" />
              </packageSource>
              <packageSource key="nuget.org">
                <package pattern="*" />
              </packageSource>
            </packageSourceMapping>
            <config>
              <add key="globalPackagesFolder" value="$(Build.SourcesDirectory)/packages" />
            </config>
            <packageRestore>
              <add key="enabled" value="True" />
              <add key="automatic" value="True" />
            </packageRestore>
          </configuration>
          EOF

    # # Build project
    # - task: DotNetCoreCLI@2
    #   displayName: 'Build Main API'
    #   inputs:
    #     command: 'build'
    #     projects: '${{ parameters.projectPath }}'
    #     arguments: '--configuration Release'

    - task: FileTransform@2
      displayName: 'Write App Settings to File'
      inputs:
        folderPath: 'backend/CPS.ComplexCases.API.Integration.Tests'
        enableXmlTransform: false
        jsonTargetFiles: appsettings.template.json

    - script: mv backend/CPS.ComplexCases.API.Integration.Tests/appsettings.template.json backend/CPS.ComplexCases.API.Integration.Tests/appsettings.json
      displayName: 'Rename Appsettings File'

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: 'backend/CPS.ComplexCases.API.Integration.Tests/CPS.ComplexCases.API.Integration.Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage;Format=cobertura" --settings backend/CodeCoverage.runsettings'
        publishTestResults: true
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        testRunTitle: 'Integration Tests'
        workingDirectory: '$(Build.SourcesDirectory)'
        resultsDirectory: '$(testResultsDirectory)'

    - task: PublishCodeCoverageResults@2
      displayName: 'Publish Code Coverage'
      inputs:
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
        failIfCoverageEmpty: true
      condition: succeededOrFailed()
