resources:
  pipelines:
  - pipeline: build
    source: 'LACC-BE-build'
    trigger: 
      branches:
        include:
          - main

variables:
  - group: lacc-deployment-global

stages:
  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: dev
      requireValidation: false
  
  - stage: Run_E2e_Tests
    displayName: 'Run E2E Tests'
    jobs:
    - template: ../templates/e2e-postman-job.yml
      parameters:
        environment: dev

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: $(preprodNotifyUsers)
      approvers: $(preprodApprovers)
      deployToSlot: true
      slotName: 'stg'
      runPostmanSmokeTest: true

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: prod
      requireValidation: true
      notifyUsers: $(prodNotifyUsers)
      approvers: $(prodApprovers)
      agentPool: 'LACC Prod Pool'
      azureSubscription: 'Azure Pipeline: Large and Complex Cases - Prod'
      deployToSlot: true
      slotName: 'stg'