resources:
  pipelines:
  - pipeline: build
    source: 'LACC-BE-build'
    trigger: 
      branches:
        include:
          - main

variables:
  - group: lacc-deployment-global

stages:
  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: dev
      requireValidation: false
      deployToSlot: true
      slotName: 'stg'

  - template: ../templates/backend-deploy-stages.yml
    parameters:
      environment: staging
      requireValidation: true
      notifyUsers: $(notifyUsers)
      approvers: $(approvers)

  # - template: ../templates/backend-deploy-stages.yml
  #   parameters:
  #     environment: prod
  #     requireValidation: true
  #     notifyUsers: $(notifyUsers)
  #     approvers: $(approvers)
  #     agentPool: 'LACC Production Pool'
  #     azureSubscription: 'Azure Pipeline: Large and Complex Cases - Prod'