// <auto-generated />
using System;
using System.Text.Json;
using CPS.ComplexCases.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CPS.ComplexCases.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250618064158_ActivityLogIndexes")]
    partial class ActivityLogIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CPS.ComplexCases.Data.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<int?>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_name");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("idx_activity_log_action_type");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("idx_activity_log_resource_id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("idx_activity_log_timestamp");

                    b.HasIndex("UserName")
                        .HasDatabaseName("idx_activity_log_user_name");

                    b.ToTable("activity_log", "large_complex_cases");
                });

            modelBuilder.Entity("CPS.ComplexCases.Data.Entities.CaseMetadata", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CaseId"));

                    b.Property<Guid?>("ActiveTransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_transfer_id");

                    b.Property<string>("EgressWorkspaceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("egress_workspace_id");

                    b.Property<string>("NetappFolderPath")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("netapp_folder_path");

                    b.HasKey("CaseId");

                    b.ToTable("case_metadata", "large_complex_cases");
                });
#pragma warning restore 612, 618
        }
    }
}
