# Build and test code on PR against main for LACC UI React web app.
# NB triggered through build policy on the 'main' branch in Azure DevOps
trigger: none

stages:
  - stage: Build_and_Test_on_PR
    displayName: 'Build and test on PR'
    jobs:
      - job: Build_and_Test
        pool:
          vmImage: ubuntu-latest

        steps:
          - script: ls -la /home/vsts/work/1/s/
            displayName: 'List directory contents'

          - task: Npm@1
            displayName: Install npm dependencies
            inputs:
              command: 'install'
              workingDir: '/home/vsts/work/1/s/ui-spa'

          - task: Npm@1
            displayName: Build web app package
            inputs:
              command: 'custom'
              customCommand: 'run build'
              workingDir: '/home/vsts/work/1/s/ui-spa'

          - task: Npm@1
            displayName: Run tests
            env:
              CI: 'true'
            inputs:
              command: 'custom'
              customCommand: 'test'
              workingDir: '/home/vsts/work/1/s/ui-spa'
